### ISSUE TITLE
Mermaid diagrams placement and background colors

### ISSUE THREAD

**Issue by Lorenzoss** [hungsu/typomagical-obsidian#25]
These bugs are also present in the default theme. However, they seem to be quite fast-forward to fix.

## Placement
When the graphs are wider than text width they are shifted to the right.

<img src="https://i.imgur.com/nMzxhiZ.png" width=50%>

It's easy to [fix](https://i.imgur.com/LjNwWv3.png) with something like that:
```css
.statediagram{
  max-width: 100%;
  display: block;
  margin-left: auto;
  margin-right: auto;
}
```

## Background colors on dark themes
On the dark variation of the themes the background colors of the boxes seem to be broken:

<img src="https://user-images.githubusercontent.com/27557209/145621468-0e8f7e6f-c71f-4e13-96da-5a478a2d8aa6.png" width=50%>

This is issue it's a little more tricky.
You can easily change the fill color with:
```css
.statediagram-cluster.statediagram-cluster .inner{
  fill: var(--background-secondary) !important;
}
.statediagram-cluster.statediagram-cluster-alt .inner{
  fill: var(--background-secondary-alt) !important;
}
```
but as you can see you need to use `!important`. I didn't find a way to avoid it.
