### ISSUE TITLE
Add styling for new callout feature

### ISSUE THREAD

**Issue by laurastephsmith** [hungsu/typomagical-obsidian#40]
v0.14.0 (currently in beta) offers callout boxes (https://help.obsidian.md/How+to/Use+callouts). It would be brilliant if you could support these to look stylish and at home in Typomagical! Black and white? Not so modern-looking?

**Comment by laurastephsmith** [comment]
I've done this as a starter, but maybe you can prettify it a bit more!

```css
.theme-light .callout {
    --callout-color: 207, 207, 207 !important;
    background-color: #ffffff !important;
    border: 1px solid rgb(207, 207, 207);
}

.theme-light .callout .callout-title .callout-icon {
    color: #2E3338;
}

.theme-dark .callout {
    --callout-color: 51, 51, 51 !important;
    background-color: transparent !important;
    border: 1px solid rgb(51, 51, 51);
}

.theme-dark .callout .callout-title .callout-icon {
    color: #DCDDDE;
}
```
