### ISSUE TITLE
Problem with Long Filenames

### ISSUE THREAD

**Issue by Onint** [hungsu/typomagical-obsidian#63]
I think Typomagical has an issue regarding long filenames; here is a screenshot

![Typomagical](https://github.com/hungsu/typomagical-obsidian/assets/135346762/ed017d79-d890-49f4-931b-c06a0cef458f)

here are the same files in default theme

![Default](https://github.com/hungsu/typomagical-obsidian/assets/135346762/acc3f861-4633-44cd-8311-5c5ccaf1640b)

And a question: I liked typomagical's fonts; can we toggle between typomagical's set of fonts and those I have assigned in Obsidian?

**Comment by hungsu** [comment]
> can we toggle between typomagical's set of fonts and those I have assigned in Obsidian?

The fonts in Obsidian's Appearance tab are overrides - that is, they're intended to override whatever the theme specifies. You could possibly use a CSS snippet to say something like "ignore font override"

```CSS
body {
--font-interface: var(--font-interface-theme), var(--default-font, '??'), var(--font-default);
--font-text: var(--font-text-theme), var(--font-interface);
}
```
