### ISSUE TITLE
Tables elements alignment

### ISSUE THREAD

**Issue by Lorenzoss** [hungsu/typomagical-obsidian#8]
I'm not sure this is an issue (it may be a _feature_ ?) but it's not possible to choose the alignment of the elements of the tables due to `text-align: left` in:
```css
.markdown-preview-view td,
.markdown-preview-view th {
  text-align: left;
  border-right-color: transparent;
  border-left-color: transparent;
}
```

**Expected behavior:**
<img src="https://i.imgur.com/Zwy7QyL.png" width=50% height=50%>

**Actual behavior:**
<img src="https://i.imgur.com/qHvytdu.png" width=50% height=50%>

Markdown:
```markdown
|                     |     Cellula Procariote     |   Cellula Eucariote   |
| ------------------- |:--------------------------:|:---------------------:|
| Dimensioni          |          1-10 μm           |       5-100 μm        | 
| DNA                 | Circolare, nel *nucleoide* | Lineare, nel *nucleo* |
| Nucleo              |          Assente           |       Presente        |
| Involucro nucleare  |          Assente           |       Presente        |
| Organelli           |          Assente           |       Presente        |
| Citoscheletro       |          Assente           |       Presente        |
| Dimensione ribosomi |            70S             |          80S          |

```
